---
title: "Quiz1_212252969"
format: html
author: niv ben arie
id: 212252969
---

# Part A:

### Q1: answer 2

### Q2: answer 1

### Q3: answer 1

# Part B:

### Q1:

```{bash#| eval: false}
cp -r ~/Downloads/ADS\ Q1-20260504 ~
mkdir ANS1/
cp ADS_Q1/NEW_DATA/ecommerce_product_dataset.csv ANS1/
mv ANS1/ecommerce_product_dataset.csv ANS1/DF1.csv
rm -r Report
```

### Q2.1:

```{r}
data <- read.csv("C:/Users/nivba/Downloads/ADS Q1-20260504/ANS1/DF1.csv")
data_selected <- data[, c(1:3, 8)]
data_selected
```

### Q2.2:

#### Option 1

```{r}
item <- data[nrow(data) - 2, ]

if (item$Discount > 0) {
  item$Price * item$Discount
} else {
  "No discount"
}
```

#### Option 2:

```{r}
#third row from end
item <- data[nrow(data) -2, ]
item

#check discount - 0.02%
item$Discount

#discount amount
discount_amount <- item$Price * item$Discount
discount_amount
```

### Q3.1

```{r}
#counting every category
count <- table(data$Category)
count

#selecting the wanted catergories
selected <- count[c("Flags", "Cookware", "Electronics")]
selected

#which ordered less
which.min(selected)

### Flags ordered less - only 1, the rest 40 each
```

### Q3.2:

```{r}
flags1 <- data[data$Category=="Flags",]
flags1
#row 712 contains Flags
```

### Q4:

```{bash#| eval: false}
git init
git add .
git commit -m "quiz commits"
git remote add https://github.com/nivbenar/Quiz1_Niv.git
git branch -M main 
git push -u origin main 
```

My GitHub repository:\
[My GitHub repository](https://github.com/nivbenar/Quiz1_Niv)

# Q5:

```{bash#| eval: false}
git clone https://github.com/nivbenar/Quiz1_Niv.git
```
